/**
 * 配置页视图提供者 (Config Page View Provider)
 *
 * 在首次启动时或用户手动打开时显示配置页，引导用户填写 LLM API 密钥等必要配置，
 * 避免让用户去 Settings 页面编写 JSON 配置。
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { localize } from './i18n';
import type { ConfigValues, WorkspaceInfo } from './webview/configPage/types';

/** Build EasyPaper agents YAML content from AgentSociety2 config (LLM/VLM). API Base uses llmApiBase. */
function buildEasyPaperYaml(config: Partial<ConfigValues>): string {
  const llmKey = (config.easypaperLlmApiKey ?? '').trim() || (config.llmApiKey ?? '').trim();
  const llmBase = (config.llmApiBase ?? 'https://cloud.infini-ai.com/maas/v1').trim();
  const llmModel = (config.easypaperLlmModel ?? '').trim() || (config.llmModel ?? 'qwen3-next-80b-a3b-instruct').trim();
  const vlmModel = (config.easypaperVlmModel ?? '').trim() || 'qwen3-vl-235b-a22b-thinking';
  const vlmKey = (config.easypaperVlmApiKey ?? '').trim() || llmKey;
  const vlmBase = llmBase;
  const esc = (s: string) => (s.includes(':') || s.includes('"') || s.includes('\n') ? `"${String(s).replace(/"/g, '\\"')}"` : s);
  const lines: string[] = [
    '# Generated by AgentSociety2. Use with EasyPaper: AGENT_CONFIG_PATH=<path-to-this-file>',
    'agents:',
    '  - name: paper_parser',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: template_parser',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: commander',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: writer',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '    writer_config:',
    '      max_review_iterations: 2',
    '      enable_review: true',
    '      enable_tools: true',
    '      available_tools:',
    '        - validate_citations',
    '        - count_words',
    '        - check_key_points',
    '  - name: typesetter',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: metadata',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '    metadata_config:',
    '      enable_mini_review: true',
    '      max_review_iterations: 2',
    '  - name: reviewer',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: planner',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: vlm_review',
    '    model:',
    `      model_name: ${esc(vlmModel)}`,
    `      api_key: ${esc(vlmKey)}`,
    `      base_url: ${esc(vlmBase)}`,
    '    vlm_review_config:',
    '      enabled: true',
    '      provider: openai',
    `      vlm_model: ${esc(vlmModel)}`,
    `      vlm_api_key: ${esc(vlmKey)}`,
    `      vlm_base_url: ${esc(vlmBase)}`,
    '      render_dpi: 150',
    '      max_pages_to_analyze: 12',
    '      check_overflow: true',
    '      check_underfill: true',
    '      check_layout: false',
    '      min_fill_percentage: 0.85',
    '      max_blank_area: 0.15',
  ];
  return lines.join('\n');
}

export class ConfigPageViewProvider {
  public static currentPanel: ConfigPageViewProvider | undefined;
  private static readonly viewType = 'aiSocialScientistConfigPage';

  private readonly _panel: vscode.WebviewPanel;
  private readonly _extensionPath: string;
  private readonly _context: vscode.ExtensionContext;
  private _disposables: vscode.Disposable[] = [];

  public static createOrShow(
    context: vscode.ExtensionContext,
    viewColumn: vscode.ViewColumn = vscode.ViewColumn.One
  ): void {
    if (ConfigPageViewProvider.currentPanel) {
      ConfigPageViewProvider.currentPanel._panel.reveal(viewColumn);
      return;
    }

    const panel = vscode.window.createWebviewPanel(
      ConfigPageViewProvider.viewType,
      localize('configPage.title'),
      viewColumn,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [
          vscode.Uri.file(path.join(context.extensionPath, 'out', 'webview'))
        ]
      }
    );

    ConfigPageViewProvider.currentPanel = new ConfigPageViewProvider(panel, context);
  }

  private constructor(panel: vscode.WebviewPanel, context: vscode.ExtensionContext) {
    this._panel = panel;
    this._context = context;
    this._extensionPath = context.extensionPath;

    this._panel.webview.html = this._getHtmlForWebview(this._panel.webview);

    this._panel.onDidDispose(() => this.dispose(), null, this._disposables);

    this._panel.webview.onDidReceiveMessage(
      async (message: { command: string; config?: Partial<ConfigValues> }) => {
        switch (message.command) {
          case 'requestConfig':
            await this._sendInitialConfig();
            break;
          case 'saveConfig':
            await this._handleSaveConfig(message.config || {});
            break;
          case 'openVscodeSettings':
            await vscode.commands.executeCommand('workbench.action.openSettings', '@aiSocialScientist');
            break;
          case 'openFolder':
            await vscode.commands.executeCommand('workbench.action.files.openFolder');
            break;
        }
      },
      null,
      this._disposables
    );
  }

  private async _sendInitialConfig(): Promise<void> {
    const config = vscode.workspace.getConfiguration('aiSocialScientist');
    const backendConfig = config.get('backend', {}) as Record<string, unknown>;
    const envConfig = config.get('env', {}) as Record<string, unknown>;

    const configValues: Partial<ConfigValues> = {
      llmApiKey: (envConfig?.llmApiKey as string) || '',
      backendHost: (envConfig?.backendHost as string) || '127.0.0.1',
      backendPort: (envConfig?.backendPort as number) ?? 8001,
      pythonPath: (backendConfig?.pythonPath as string) || '',
      llmApiBase: (envConfig?.llmApiBase as string) || 'https://cloud.infini-ai.com/maas/v1',
      llmModel: (envConfig?.llmModel as string) || 'qwen3-next-80b-a3b-instruct',
      backendLogLevel: (envConfig?.backendLogLevel as string) || 'info',
      coderLlmApiKey: (envConfig?.coderLlmApiKey as string) || '',
      coderLlmApiBase: (envConfig?.coderLlmApiBase as string) || '',
      coderLlmModel: (envConfig?.coderLlmModel as string) || 'glm-4.7',
      nanoLlmApiKey: (envConfig?.nanoLlmApiKey as string) || '',
      nanoLlmApiBase: (envConfig?.nanoLlmApiBase as string) || '',
      nanoLlmModel: (envConfig?.nanoLlmModel as string) || 'qwen3-next-80b-a3b-instruct',
      embeddingApiKey: (envConfig?.embeddingApiKey as string) || '',
      embeddingApiBase: (envConfig?.embeddingApiBase as string) || '',
      embeddingModel: (envConfig?.embeddingModel as string) || 'bge-m3',
      embeddingDims: (envConfig?.embeddingDims as number) ?? 1024,
      webSearchApiUrl: (envConfig?.webSearchApiUrl as string) || '',
      webSearchApiToken: (envConfig?.webSearchApiToken as string) || '',
      miroflowDefaultLlm: (envConfig?.miroflowDefaultLlm as string) || 'qwen-3',
      miroflowDefaultAgent: (envConfig?.miroflowDefaultAgent as string) || 'mirothinker_v1.5_keep5_max200',
      easypaperApiUrl: (envConfig?.easypaperApiUrl as string) || '',
      easypaperLlmApiKey: (envConfig?.easypaperLlmApiKey as string) || '',
      easypaperLlmModel: (envConfig?.easypaperLlmModel as string) || 'qwen3-next-80b-a3b-instruct',
      easypaperVlmModel: (envConfig?.easypaperVlmModel as string) || 'qwen3-vl-235b-a22b-thinking',
      easypaperVlmApiKey: (envConfig?.easypaperVlmApiKey as string) || '',
      literatureSearchApiUrl: (envConfig?.literatureSearchApiUrl as string) || 'http://localhost:8002/api/v1/search',
    };

    // 获取工作区信息
    const workspaceInfo: WorkspaceInfo = {
      hasWorkspace: !!(vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 0),
      workspacePath: vscode.workspace.workspaceFolders?.[0]?.uri.fsPath
    };

    this._panel.webview.postMessage({
      command: 'initialConfig',
      config: configValues
    });

    this._panel.webview.postMessage({
      command: 'workspaceInfo',
      workspaceInfo: workspaceInfo
    });
  }

  private async _handleSaveConfig(config: Partial<ConfigValues>): Promise<void> {
    try {
      // 检查是否有工作区
      if (!vscode.workspace.workspaceFolders || vscode.workspace.workspaceFolders.length === 0) {
        this._panel.webview.postMessage({
          command: 'saveResult',
          success: false,
          error: localize('configPage.noWorkspace')
        });
        return;
      }
      const vscodeConfig = vscode.workspace.getConfiguration('aiSocialScientist');

      if (config.llmApiKey !== undefined) {
        await vscodeConfig.update('env.llmApiKey', config.llmApiKey, vscode.ConfigurationTarget.Workspace);
      }
      if (config.backendHost !== undefined) {
        await vscodeConfig.update('env.backendHost', config.backendHost, vscode.ConfigurationTarget.Workspace);
      }
      if (config.backendPort !== undefined) {
        await vscodeConfig.update('env.backendPort', config.backendPort, vscode.ConfigurationTarget.Workspace);
      }
      if (config.pythonPath !== undefined) {
        await vscodeConfig.update('backend.pythonPath', config.pythonPath, vscode.ConfigurationTarget.Workspace);
      }
      if (config.llmApiBase !== undefined) {
        await vscodeConfig.update('env.llmApiBase', config.llmApiBase, vscode.ConfigurationTarget.Workspace);
      }
      if (config.llmModel !== undefined) {
        await vscodeConfig.update('env.llmModel', config.llmModel, vscode.ConfigurationTarget.Workspace);
      }
      if (config.backendLogLevel !== undefined) {
        await vscodeConfig.update('env.backendLogLevel', config.backendLogLevel, vscode.ConfigurationTarget.Workspace);
      }
      if (config.coderLlmApiKey !== undefined) {
        await vscodeConfig.update('env.coderLlmApiKey', config.coderLlmApiKey, vscode.ConfigurationTarget.Workspace);
      }
      if (config.coderLlmApiBase !== undefined) {
        await vscodeConfig.update('env.coderLlmApiBase', config.coderLlmApiBase, vscode.ConfigurationTarget.Workspace);
      }
      if (config.coderLlmModel !== undefined) {
        await vscodeConfig.update('env.coderLlmModel', config.coderLlmModel, vscode.ConfigurationTarget.Workspace);
      }
      if (config.nanoLlmApiKey !== undefined) {
        await vscodeConfig.update('env.nanoLlmApiKey', config.nanoLlmApiKey, vscode.ConfigurationTarget.Workspace);
      }
      if (config.nanoLlmApiBase !== undefined) {
        await vscodeConfig.update('env.nanoLlmApiBase', config.nanoLlmApiBase, vscode.ConfigurationTarget.Workspace);
      }
      if (config.nanoLlmModel !== undefined) {
        await vscodeConfig.update('env.nanoLlmModel', config.nanoLlmModel, vscode.ConfigurationTarget.Workspace);
      }
      if (config.embeddingApiKey !== undefined) {
        await vscodeConfig.update('env.embeddingApiKey', config.embeddingApiKey, vscode.ConfigurationTarget.Workspace);
      }
      if (config.embeddingApiBase !== undefined) {
        await vscodeConfig.update('env.embeddingApiBase', config.embeddingApiBase, vscode.ConfigurationTarget.Workspace);
      }
      if (config.embeddingModel !== undefined) {
        await vscodeConfig.update('env.embeddingModel', config.embeddingModel, vscode.ConfigurationTarget.Workspace);
      }
      if (config.embeddingDims !== undefined) {
        await vscodeConfig.update('env.embeddingDims', config.embeddingDims, vscode.ConfigurationTarget.Workspace);
      }
      if (config.webSearchApiUrl !== undefined) {
        await vscodeConfig.update('env.webSearchApiUrl', config.webSearchApiUrl, vscode.ConfigurationTarget.Workspace);
      }
      if (config.webSearchApiToken !== undefined) {
        await vscodeConfig.update('env.webSearchApiToken', config.webSearchApiToken, vscode.ConfigurationTarget.Workspace);
      }
      if (config.miroflowDefaultLlm !== undefined) {
        await vscodeConfig.update('env.miroflowDefaultLlm', config.miroflowDefaultLlm, vscode.ConfigurationTarget.Workspace);
      }
      if (config.miroflowDefaultAgent !== undefined) {
        await vscodeConfig.update('env.miroflowDefaultAgent', config.miroflowDefaultAgent, vscode.ConfigurationTarget.Workspace);
      }
      if (config.easypaperApiUrl !== undefined) {
        await vscodeConfig.update('env.easypaperApiUrl', config.easypaperApiUrl, vscode.ConfigurationTarget.Workspace);
      }
      if (config.easypaperLlmApiKey !== undefined) {
        await vscodeConfig.update('env.easypaperLlmApiKey', config.easypaperLlmApiKey, vscode.ConfigurationTarget.Workspace);
      }
      if (config.easypaperLlmModel !== undefined) {
        await vscodeConfig.update('env.easypaperLlmModel', config.easypaperLlmModel, vscode.ConfigurationTarget.Workspace);
      }
      if (config.easypaperVlmModel !== undefined) {
        await vscodeConfig.update('env.easypaperVlmModel', config.easypaperVlmModel, vscode.ConfigurationTarget.Workspace);
      }
      if (config.easypaperVlmApiKey !== undefined) {
        await vscodeConfig.update('env.easypaperVlmApiKey', config.easypaperVlmApiKey, vscode.ConfigurationTarget.Workspace);
      }
      if (config.literatureSearchApiUrl !== undefined) {
        await vscodeConfig.update('env.literatureSearchApiUrl', config.literatureSearchApiUrl, vscode.ConfigurationTarget.Workspace);
      }

      // If EasyPaper URL or any model field is set, write easypaper_agentsociety.yaml to workspace for EasyPaper to use
      const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
      const hasEasyPaperConfig =
        (config.easypaperApiUrl ?? '').trim() !== '' ||
        (config.easypaperLlmModel ?? '').trim() !== '' ||
        (config.easypaperLlmApiKey ?? '').trim() !== '' ||
        (config.easypaperVlmModel ?? '').trim() !== '';
      if (workspaceFolder && hasEasyPaperConfig) {
        try {
          const yamlPath = path.join(workspaceFolder.uri.fsPath, 'easypaper_agentsociety.yaml');
          const yamlContent = buildEasyPaperYaml(config);
          fs.writeFileSync(yamlPath, yamlContent, 'utf8');
        } catch (e) {
          console.warn('Failed to write easypaper_agentsociety.yaml:', e);
        }
      }

      // 标记已完成初始配置
      await this._context.globalState.update('configPage.hasCompletedInitialSetup', true);

      this._panel.webview.postMessage({ command: 'saveResult', success: true });

      // 启动后端服务
      await vscode.commands.executeCommand('aiSocialScientist.startBackend');
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this._panel.webview.postMessage({
        command: 'saveResult',
        success: false,
        error: message
      });
    }
  }

  private _getHtmlForWebview(webview: vscode.Webview): string {
    const scriptUri = webview.asWebviewUri(
      vscode.Uri.file(path.join(this._extensionPath, 'out', 'webview', 'configPage.js'))
    );

    return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource} 'unsafe-inline'; script-src ${webview.cspSource} 'unsafe-eval' 'unsafe-inline';">
  <title>${localize('configPage.title')}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: var(--vscode-font-family, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif);
      background: var(--vscode-editor-background);
      color: var(--vscode-editor-foreground);
      height: 100vh;
      overflow: auto;
    }
    #root { min-height: 100vh; }
  </style>
</head>
<body>
  <div id="root"></div>
  <script src="${scriptUri}"></script>
</body>
</html>`;
  }

  public dispose(): void {
    ConfigPageViewProvider.currentPanel = undefined;
    while (this._disposables.length) {
      const d = this._disposables.pop();
      if (d) d.dispose();
    }
  }
}
